-- Generated from generator/demo_specs/aws-philippines-banking-branch.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-banking-branch
-- This is the schema that is actually deployed for PH_BANKING_BRANCH.

-- Alerts fire on the bottom tail of Digital Adoption
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_DIGITAL_ADOPTION) AS T
  FROM RAW.TRANSACTIONS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_DIGITAL_ADOPTION <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_DIGITAL_ADOPTION), 2) AS AVG_DIGITAL_ADOPTION,
  ROUND(AVG(f.KPI_NPS_SCORE), 2) AS AVG_NPS_SCORE,
  ROUND(AVG(f.KPI_BRANCH_TO_DIGITAL_SHIFT), 2) AS AVG_BRANCH_TO_DIGITAL_SHIF
FROM RAW.TRANSACTIONS f
JOIN RAW.BSP_BANKING_DATA e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_DIGITAL_ADOPTION), 2) AS AVG_DIGITAL_ADOPTION,
  ROUND(AVG(f.KPI_NPS_SCORE), 2) AS AVG_NPS_SCORE,
  ROUND(AVG(f.KPI_BRANCH_TO_DIGITAL_SHIFT), 2) AS AVG_BRANCH_TO_DIGITAL_SHIF
FROM RAW.TRANSACTIONS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_DIGITAL_ADOPTION) AS KPI_DIGITAL_ADOPTION, AVG(KPI_NPS_SCORE) AS KPI_NPS_SCORE, AVG(KPI_BRANCH_TO_DIGITAL_SHIFT) AS KPI_BRANCH_TO_DIGITAL_SHIFT FROM RAW.TRANSACTIONS),
     en AS (SELECT SUM(KPI_BRANCH_REVENUE) AS KPI_BRANCH_REVENUE, SUM(KPI_BRANCHES_ACTIVE) AS KPI_BRANCHES_ACTIVE, SUM(KPI_MOBILE_BANKING_USERS) AS KPI_MOBILE_BANKING_USERS, SUM(KPI_COST_PER_TRANSACTION) AS KPI_COST_PER_TRANSACTION FROM RAW.BSP_BANKING_DATA)
  SELECT 1 AS SORT_ORDER, 'Branch Revenue' AS TITLE, KPI_BRANCH_REVENUE AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_BRANCH_REVENUE) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Digital Adoption' AS TITLE, KPI_DIGITAL_ADOPTION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DIGITAL_ADOPTION)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'NPS Score' AS TITLE, KPI_NPS_SCORE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_NPS_SCORE)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Branches Active' AS TITLE, KPI_BRANCHES_ACTIVE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_BRANCHES_ACTIVE)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Mobile Banking Users' AS TITLE, KPI_MOBILE_BANKING_USERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_MOBILE_BANKING_USERS) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Branch-to-Digital Shift' AS TITLE, KPI_BRANCH_TO_DIGITAL_SHIFT AS VALUE_NUM, '+' || TO_VARCHAR(CAST(ROUND((KPI_BRANCH_TO_DIGITAL_SHIFT)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Cost per Transaction' AS TITLE, KPI_COST_PER_TRANSACTION AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND((KPI_COST_PER_TRANSACTION)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
