-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Branch Network Optimization & Demand Forecasting
-- ============================================================================
USE DATABASE BRANCH_NETWORK;
USE SCHEMA ML;

-- ML.FORECAST: BRANCH_DEMAND_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.BRANCH_DEMAND_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.DEMAND_TIMESERIES'),
  SERIES_COLNAME => 'BRANCH_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'DAILY_TRANSACTIONS'
  
);

CREATE OR REPLACE TABLE ML.BRANCH_DEMAND_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.BRANCH_DEMAND_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.CLASSIFICATION: BRANCH_VIABILITY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.BRANCH_VIABILITY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.EXPANSION_CANDIDATES'),
  TARGET_COLNAME => 'PROFITABLE_WITHIN_2Y'
);

