-- ============================================================================
-- 99_RESET.SQL — Reset Branch Network Optimization & Demand Forecasting to clean demo state
-- ============================================================================
USE DATABASE BRANCH_NETWORK;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_TRAFFIC SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_CATCHMENTS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_DEMAND SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.BRANCH_PERFORMANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.CATCHMENT_ANALYSIS REFRESH;
ALTER DYNAMIC TABLE CURATED.DEMAND_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.EXPANSION_CANDIDATES REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM BRANCH_NETWORK.RAW.BRANCHES → 850
-- SELECT COUNT(*) FROM BRANCH_NETWORK.RAW.TRANSACTIONS → 12000000
-- SELECT COUNT(*) FROM BRANCH_NETWORK.CURATED.BRANCH_PERFORMANCE WHERE ROI_PCT < 0 → 124

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_FORECAST_DEMAND RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_CATCHMENTS RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_TRAFFIC RESUME;
